version: '3.5'
services:

  mongodb:
    image : mongo:3.6.8
    container_name: krok-mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

  krokapi:
    image: krokapi:latest
    container_name: krok-krokapi
    environment:
      - MONGO_URL=mongodb://krok-mongodb:27017
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    restart: unless-stopped
