version: 2.1

orbs:
  node: circleci/node@4.1.0
  codecov: codecov/codecov@1.1.3

jobs:
  build-production:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install --production
      - run: npm run build
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  prettier:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run: npm run prettier
      - persist_to_workspace:
          root: .
          paths:
            - .
  eslint:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run: npm t
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_artifacts:
          path: coverage

workflows:
  api_tests_and_coverage:
    jobs:
      - build
      - build-production
      - prettier:
          requires:
            - build
      - eslint:
          requires:
            - build
      - test:
          requires:
            - eslint
      - codecov/upload:
          file: "coverage/clover.xml"
          requires:
            - test
