version: '3.2'
services:

  mongodb:
    image : mongo:3.6.8
    container_name: krok-mongodb-dev
    volumes:
      - ../volumes/mongodb-dev/data/db:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

  krokapi:
    image: krok/api-dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-dev
    container_name: krok-krokapi-dev
    environment:
      - MONGO_URL=mongodb://krok-mongodb-dev:27017
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    restart: unless-stopped
